- type: replace
  path: /instance_groups/name=jenkins-master/jobs/name=jenkins-master/properties/config/enforced?
  value:
    credentials:
      system:
        domainCredentials:
          - credentials:
              - basicSSHUserPrivateKey:
                  scope: GLOBAL
                  id: enforced-ssh-credential
                  username: enforced-ssh-user
                  description: "SSH credential added via enforced config"
                  privateKeySource:
                    directEntry:
                      privateKey: ((ssh_credential.private_key))
