jenkins:
  globalNodeProperties:
    - envVars:
        env:
        - (( append ))
        # Note the append above, so as to not overwrite anything from manifest
        - key: "VarFromRepo"
          value: "some-value"
