jenkins:
  authorizationStrategy:
    projectMatrix:
      grantedPermissions:
      - "Agent/Build:slave"
      - "Agent/Configure:slave"
      - "Agent/Connect:slave"
      - "Agent/Create:slave"
      - "Agent/Delete:slave"
      - "Agent/Disconnect:slave"
      - "Overall/Administer:admin"
      - "Job/Discover:authenticated"
      - "Overall/Read:authenticated"
      - "Overall/Read:slave"
  disableRememberMe: true
unclassified:
  simple-theme-plugin:
    elements:
    - cssUrl:
        url: "/userContent/branding.css"
