- type: replace
  path: /instance_groups/name=jenkins-master/jobs/name=jenkins-master/properties/config/repository/ssh_key?
  value: ((config_repo_ssh_key))

- type: replace
  path: /variables/name=config_repo_ssh_key?/type
  value: ssh
